backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

    
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Features Post", name: "featuredpost", widget: "boolean", default: true}
      - {label: "Article", name: "article", widget: object, fields: [
        {label: "Title", name: "title", widget: string},
        {label: "Date", name: "date", widget: date},
        {label: "URL", name: "url", widget: string},
        {label: "Thumbnail", name: "thumbnail", widget: image}
      ]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "landingPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "landing-page"}
          - {label: "Title", name: title, widget: string, default: "Do something"}
          
      - file: "src/content/about/index.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "about"}
          - {label: "About Page", name: aboutPage, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Paragraph 1", name: paragraph1, widget: string},
            {label: "Paragraph 2", name: paragraph2, widget: string},
            {label: "Signature", name: signature, widget: string},
            {label: "Hero Image", name: hero, widget: image},
            {label: "Body Image Left", name: bodyImageLeft, widget: image},
            {label: "Body Image Right", name: bodyImageRight, widget: image},
          ]}
      - file: "src/content/contact/index.md"
        label: "Contact Page"
        name: "contactPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "contact"}
          - {label: "Contact Page", name: contactPage, widget: object, fields: [
            {label: "Contact Form", name: contactForm, widget: object, fields: [
              {label: "Location", name: location, widget: string},
              {label: "Telephone", name: telephone, widget: string},
              {label: "Email", name: email, widget: string},
              {label: "Address Line 1", name: addressLine1, widget: string},
              {label: "Address Line 2", name: addressLine2, widget: string},
            ]},
            {label: "Employment Information", name: employment, widget: object, fields: [
              {label: "Title", name: title, widget: string},
              {label: "Description", name: description, widget: string},
            ]},
          ]}
      - file: "src/content/pricing/index.md"
        label: "Pricing Page"
        name: "pricingPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "contact"}
          - {label: "Pricing Page", name: pricingPage, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Description", name: description, widget: string},
            {label: "Cards", name: cards, widget: list, fields: [
              {label: "Title", name: title, widget: string},
              {label: "Amount", name: amount, widget: number},
              {label: "Currency", name: currency, widget: string},
              {label: "Period", name: period, widget: string},
              {label: "To", name: to, widget: string},
              {label: "Features", name: features, widget: list, fields: [
                {label: "Feature", name: feature, widget: string},
              ]},
            ]},
          ]}